blank_issues_enabled: false
contact_links:
  - name: Anything else (excluding general support)
    url: https://github.com/araynimax
    about: Write an email to arayni.max@gmail.com. Please include "phoskin" into the subject.
